spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gradquest?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: gradquest
    password: gradquest
    driver-class-name: com.mysql.cj.jdbc.Driver

app:
  client-origins: "*"
  jwt:
    secret: "/PRy6kwavSNo9NfK6bJ7uhTeg6cyJ6r8Zg1jg/qzPkY="
